### ISSUE TITLE
AFNetworking outdated dependency

### ISSUE THREAD

**Issue by akiokio** [pagarme/pagarme-ios#4]
Hey guys, your podspec file is outdated, AFNetworking has been updated to v3 and broke compatibility with the lib.

Please update your podspec to ensure the correct version of the last supported AFNetworking or update the lib itself.

E.g. `spec.dependency 'AFNetworking', '~> 2.5'`

If you want I can open a PR.

Thanks

**Comment by lucianocn** [comment]
@akiokio It sounds good upgrade to AFNetworking 3.0. You can do it and open a PR?

@pedrofranceschi check here please.

**Comment by ppamorim** [comment]
I don't know if a library to network requests is needed. What do you think to make this feature out-of-box?

**Comment by fpg1503** [comment]
Updated in #6.

**Comment by brunomunizaf** [comment]
This could be done with URLSession in < 10 lines... why an entire network library for one get request?
