### ISSUE TITLE
CardHash error

### ISSUE THREAD

**Issue by fontalland** [pagarme/pagarme-ios#7]
Após alterar o uso do pagarme-ios para o Pods, ao gerar o cardHash, recebo a seguinte string:
"214645_(null)"

Detalhe importante é que nada no código que funcionava perfeitamente foi alterado, com exceção da exclusão das classes do pagarme do projeto e inserção do mesmo através do CocoaPods.

**Comment by lucasmpaim** [comment]
Same issue here
